#!/usr/bin/env bash
vncserver -kill :*
rm -rf /username/.vnc/localhost:*.pid
rm -rf /tmp/.X1-lock
rm -rf /tmp/.X11-unix/X1
vncserver -geometry 1512x750 -localhost no :1 -pixelformat rgb888 -depth 32 -SecurityTypes None --I-KNOW-THIS-IS-INSECURE
termux-open vnc://localhost:5901
